### ISSUE TITLE
Unable to sign up with Google

### ISSUE THREAD

**Issue by ichirotski** [molmsted98/mFrame#7]
Users are unable to create an mFrame account with Google.

> Error: redirect_uri_mismatch
> The redirect URI in the request, http://www.mfra.me/auth/google/callback, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/581663096954-a8kqb1dco991p4gtaqqc8q4p973ptg19.apps.googleusercontent.com?project=581663096954 to update the authorized redirect URIs.

**Comment by molmsted98** [comment]
Before you clicked the Google API button, did you first click on log in or create account from the navigation bar?

**Comment by ichirotski** [comment]
I clicked on Create Account on the navigation bar. I just tried it again with both and seems to work, which is strange. It must've been a glitch.
